/**
 * Static knowledge used by detectors.
 *
 * These lists are *heuristics*, not ground truth. Faithful port of
 * ``aiprojectdetector.constants``.
 */

export const DEFAULT_IGNORE_DIRS: ReadonlySet<string> = new Set([
  "node_modules",
  "vendor",
  "bower_components",
  "build",
  "dist",
  "out",
  "target",
  ".next",
  ".nuxt",
  ".svelte-kit",
  "__pycache__",
  ".pytest_cache",
  ".mypy_cache",
  ".ruff_cache",
  ".tox",
  ".venv",
  "venv",
  "env",
  ".env",
  "site-packages",
  ".gradle",
  ".idea",
  ".vscode",
  ".cache",
  "coverage",
  "htmlcov",
  ".terraform",
  "Pods",
  "DerivedData",
  ".cargo",
  ".git",
  ".hg",
  ".svn",
]);

export const DEFAULT_LOCKFILES: ReadonlySet<string> = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "poetry.lock",
  "Pipfile.lock",
  "Cargo.lock",
  "composer.lock",
  "Gemfile.lock",
  "go.sum",
  "flake.lock",
]);

export const BINARY_EXTENSIONS: ReadonlySet<string> = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".tiff", ".svg",
  ".pdf", ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war",
  ".mp3", ".mp4", ".avi", ".mov", ".mkv", ".wav", ".flac", ".ogg",
  ".woff", ".woff2", ".ttf", ".otf", ".eot",
  ".so", ".dll", ".dylib", ".a", ".o", ".obj", ".exe", ".bin", ".class",
  ".pyc", ".pyo", ".wasm", ".node",
  ".db", ".sqlite", ".sqlite3", ".parquet", ".npy", ".npz", ".pkl", ".ds_store",
]);

export const GENERATED_FILE_MARKERS: readonly string[] = [
  "@generated",
  "do not edit",
  "this file is generated",
  "auto-generated",
  "autogenerated",
  "code generated by",
  "generated by protoc",
  "generated by the protocol buffer compiler",
  "// Code generated",
  "DO NOT MODIFY",
];

// --------------------------------------------------------------------------- //
// Language detection                                                           //
// --------------------------------------------------------------------------- //

export const EXTENSION_LANGUAGE: Readonly<Record<string, string>> = {
  ".py": "python",
  ".pyi": "python",
  ".js": "javascript",
  ".jsx": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".ts": "typescript",
  ".tsx": "typescript",
  ".java": "java",
  ".kt": "kotlin",
  ".go": "go",
  ".rs": "rust",
  ".rb": "ruby",
  ".php": "php",
  ".c": "c",
  ".h": "c",
  ".cc": "cpp",
  ".cpp": "cpp",
  ".cxx": "cpp",
  ".hpp": "cpp",
  ".cs": "csharp",
  ".swift": "swift",
  ".scala": "scala",
  ".sh": "shell",
  ".bash": "shell",
  ".zsh": "shell",
  ".sql": "sql",
  ".r": "r",
  ".m": "objc",
  ".lua": "lua",
  ".dart": "dart",
  ".vue": "vue",
  ".svelte": "svelte",
  ".md": "markdown",
  ".rst": "restructuredtext",
  ".yml": "yaml",
  ".yaml": "yaml",
  ".toml": "toml",
  ".json": "json",
  ".xml": "xml",
  ".html": "html",
  ".css": "css",
  ".scss": "scss",
  ".dockerfile": "dockerfile",
};

export const LINE_COMMENT_TOKENS: Readonly<Record<string, readonly string[]>> = {
  python: ["#"],
  ruby: ["#"],
  shell: ["#"],
  yaml: ["#"],
  toml: ["#"],
  r: ["#"],
  javascript: ["//"],
  typescript: ["//"],
  java: ["//"],
  kotlin: ["//"],
  go: ["//"],
  rust: ["//"],
  c: ["//"],
  cpp: ["//"],
  csharp: ["//"],
  swift: ["//"],
  scala: ["//"],
  php: ["//", "#"],
  dart: ["//"],
  sql: ["--"],
  lua: ["--"],
};

// --------------------------------------------------------------------------- //
// LLM fingerprint phrase banks                                                 //
// --------------------------------------------------------------------------- //

export const LLM_COMMENT_PHRASES: readonly string[] = [
  "this function",
  "this method",
  "this class",
  "this code",
  "here we",
  "here's how",
  "here is how",
  "in this example",
  "for example,",
  "note that",
  "please note",
  "it's important to",
  "it is important to",
  "make sure to",
  "make sure that",
  "as you can see",
  "first, we",
  "next, we",
  "finally, we",
  "step 1",
  "step 2",
  "step 3",
  "in order to",
  "we then",
  "we now",
  "let's",
  "feel free to",
  "keep in mind",
  "under the hood",
  "behind the scenes",
  "the following",
  "as follows",
  "is responsible for",
  "is used to",
  "this will",
  "this ensures",
  "this allows",
  "to do this",
  "by default",
  "out of the box",
];

export const PLACEHOLDER_MARKERS: readonly string[] = [
  "your code here",
  "your implementation here",
  "implement this",
  "implementation goes here",
  "add your logic here",
  "todo: implement",
  "todo implement",
  "fixme",
  "placeholder",
  "replace with your",
  "replace this with",
  "rest of the code",
  "rest of your code",
  "... (truncated)",
  "and so on",
  "etc.",
  "raise notimplementederror",
  'throw new error("not implemented',
  "pass  # todo",
];

export const LLM_DOC_PHRASES: readonly string[] = [
  "in today's fast-paced",
  "in the world of",
  "in this digital age",
  "harness the power",
  "unlock the power",
  "seamlessly",
  "robust and scalable",
  "cutting-edge",
  "state-of-the-art",
  "elevate your",
  "take your",
  "to the next level",
  "comprehensive solution",
  "powerful tool",
  "with ease",
  "effortlessly",
  "whether you're a",
  "designed to",
  "out of the box",
  "best practices",
  "getting started is easy",
  "happy coding",
  "this project aims to",
  "this project is designed",
  "feel free to contribute",
  "contributions are welcome",
];

export const GENERIC_README_SECTIONS: readonly string[] = [
  "features",
  "installation",
  "getting started",
  "usage",
  "prerequisites",
  "configuration",
  "api reference",
  "contributing",
  "license",
  "acknowledgements",
  "acknowledgments",
  "roadmap",
  "table of contents",
];

// --------------------------------------------------------------------------- //
// Commit-history heuristics                                                    //
// --------------------------------------------------------------------------- //

export const GENERIC_COMMIT_MESSAGES: readonly string[] = [
  "initial commit",
  "first commit",
  "update",
  "updates",
  "update files",
  "add files",
  "add files via upload",
  "fix",
  "fixes",
  "changes",
  "wip",
  "misc",
  "commit",
  "stuff",
  "final",
  "done",
  "cleanup",
  "refactor",
];

// --------------------------------------------------------------------------- //
// Speculative model-attribution profiles                                       //
// --------------------------------------------------------------------------- //

export interface AttributionProfile {
  label: string;
  phrases: readonly string[];
  tends_to: readonly string[];
}

export const ATTRIBUTION_PROFILES: Readonly<Record<string, AttributionProfile>> = {
  chatgpt: {
    label: "ChatGPT / GPT-family",
    phrases: ["certainly!", "sure!", "here's", "let's", "i hope this helps", "feel free"],
    tends_to: ["emoji in headings", "numbered step explanations", "verbose docstrings"],
  },
  claude: {
    label: "Claude-family",
    phrases: ["i'll", "let me", "here's a", "this implementation", "note that"],
    tends_to: ["structured comments", "thorough error handling", "type hints"],
  },
  gemini: {
    label: "Gemini-family",
    phrases: ["here is", "you can use", "the following code", "this snippet"],
    tends_to: ["concise comments", "markdown-heavy docs"],
  },
  copilot: {
    label: "GitHub Copilot / inline completion",
    phrases: [],
    tends_to: ["short inline completions", "boilerplate repetition", "few comments"],
  },
  other_llm: {
    label: "Other / unknown LLM",
    phrases: [],
    tends_to: [],
  },
};
