"""Static knowledge used by detectors.

These lists are *heuristics*, not ground truth. They encode patterns that are
empirically more common in LLM-generated code and prose, but every single one
of them also appears in perfectly ordinary human-written code. They are tuned
on the calibration corpus (see aiprojectdetector.scoring.calibration) and are
meant to be transparent and editable rather than hidden in a black-box model.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# Ingestion: default ignore rules                                             #
# --------------------------------------------------------------------------- #

# Directories excluded by default (dependency/build/cache noise that would
# pollute stylometry with third-party code).
DEFAULT_IGNORE_DIRS: frozenset[str] = frozenset(
    {
        "node_modules",
        "vendor",
        "bower_components",
        "build",
        "dist",
        "out",
        "target",
        ".next",
        ".nuxt",
        ".svelte-kit",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".tox",
        ".venv",
        "venv",
        "env",
        ".env",
        "site-packages",
        ".gradle",
        ".idea",
        ".vscode",
        ".cache",
        "coverage",
        "htmlcov",
        ".terraform",
        "Pods",
        "DerivedData",
        ".cargo",
        ".git",
        ".hg",
        ".svn",
    }
)

# Lockfiles are excluded unless the caller explicitly opts in: they are huge,
# machine-generated, and would swamp the stylometry signal.
DEFAULT_LOCKFILES: frozenset[str] = frozenset(
    {
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "Pipfile.lock",
        "Cargo.lock",
        "composer.lock",
        "Gemfile.lock",
        "go.sum",
        "flake.lock",
    }
)

# Binary / non-source extensions skipped during text analysis.
BINARY_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".tiff", ".svg",
        ".pdf", ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war",
        ".mp3", ".mp4", ".avi", ".mov", ".mkv", ".wav", ".flac", ".ogg",
        ".woff", ".woff2", ".ttf", ".otf", ".eot",
        ".so", ".dll", ".dylib", ".a", ".o", ".obj", ".exe", ".bin", ".class",
        ".pyc", ".pyo", ".wasm", ".node",
        ".db", ".sqlite", ".sqlite3", ".parquet", ".npy", ".npz", ".pkl", ".ds_store",
    }
)

# Files that are themselves machine-generated; flagged but not used for stylometry.
GENERATED_FILE_MARKERS: tuple[str, ...] = (
    "@generated",
    "do not edit",
    "this file is generated",
    "auto-generated",
    "autogenerated",
    "code generated by",
    "generated by protoc",
    "generated by the protocol buffer compiler",
    "// Code generated",
    "DO NOT MODIFY",
)

# --------------------------------------------------------------------------- #
# Language detection                                                           #
# --------------------------------------------------------------------------- #

EXTENSION_LANGUAGE: dict[str, str] = {
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".kt": "kotlin",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".swift": "swift",
    ".scala": "scala",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".sql": "sql",
    ".r": "r",
    ".m": "objc",
    ".lua": "lua",
    ".dart": "dart",
    ".vue": "vue",
    ".svelte": "svelte",
    ".md": "markdown",
    ".rst": "restructuredtext",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".toml": "toml",
    ".json": "json",
    ".xml": "xml",
    ".html": "html",
    ".css": "css",
    ".scss": "scss",
    ".dockerfile": "dockerfile",
}

# Line-comment and block-comment markers per language, used to extract comments.
LINE_COMMENT_TOKENS: dict[str, tuple[str, ...]] = {
    "python": ("#",),
    "ruby": ("#",),
    "shell": ("#",),
    "yaml": ("#",),
    "toml": ("#",),
    "r": ("#",),
    "javascript": ("//",),
    "typescript": ("//",),
    "java": ("//",),
    "kotlin": ("//",),
    "go": ("//",),
    "rust": ("//",),
    "c": ("//",),
    "cpp": ("//",),
    "csharp": ("//",),
    "swift": ("//",),
    "scala": ("//",),
    "php": ("//", "#"),
    "dart": ("//",),
    "sql": ("--",),
    "lua": ("--",),
}

# --------------------------------------------------------------------------- #
# LLM fingerprint phrase banks                                                 #
# --------------------------------------------------------------------------- #

# Comment / prose phrasings that show up disproportionately in LLM output.
# Matched case-insensitively. Presence of a few is meaningless; high density
# across many files is the actual signal.
LLM_COMMENT_PHRASES: tuple[str, ...] = (
    "this function",
    "this method",
    "this class",
    "this code",
    "here we",
    "here's how",
    "here is how",
    "in this example",
    "for example,",
    "note that",
    "please note",
    "it's important to",
    "it is important to",
    "make sure to",
    "make sure that",
    "as you can see",
    "first, we",
    "next, we",
    "finally, we",
    "step 1",
    "step 2",
    "step 3",
    "in order to",
    "we then",
    "we now",
    "let's",
    "feel free to",
    "keep in mind",
    "under the hood",
    "behind the scenes",
    "the following",
    "as follows",
    "is responsible for",
    "is used to",
    "this will",
    "this ensures",
    "this allows",
    "to do this",
    "by default",
    "out of the box",
)

# Placeholder / stub markers.
PLACEHOLDER_MARKERS: tuple[str, ...] = (
    "your code here",
    "your implementation here",
    "implement this",
    "implementation goes here",
    "add your logic here",
    "todo: implement",
    "todo implement",
    "fixme",
    "placeholder",
    "replace with your",
    "replace this with",
    "rest of the code",
    "rest of your code",
    "... (truncated)",
    "and so on",
    "etc.",
    "raise notimplementederror",
    "throw new error(\"not implemented",
    "pass  # todo",
)

# README / documentation phrasings characteristic of generated prose.
LLM_DOC_PHRASES: tuple[str, ...] = (
    "in today's fast-paced",
    "in the world of",
    "in this digital age",
    "harness the power",
    "unlock the power",
    "seamlessly",
    "robust and scalable",
    "cutting-edge",
    "state-of-the-art",
    "elevate your",
    "take your",
    "to the next level",
    "comprehensive solution",
    "powerful tool",
    "with ease",
    "effortlessly",
    "whether you're a",
    "designed to",
    "out of the box",
    "best practices",
    "getting started is easy",
    "happy coding",
    "this project aims to",
    "this project is designed",
    "feel free to contribute",
    "contributions are welcome",
)

# Section headings that, in this exact set and order, are typical of generated
# READMEs. Used only as a weak structural signal.
GENERIC_README_SECTIONS: tuple[str, ...] = (
    "features",
    "installation",
    "getting started",
    "usage",
    "prerequisites",
    "configuration",
    "api reference",
    "contributing",
    "license",
    "acknowledgements",
    "acknowledgments",
    "roadmap",
    "table of contents",
)

# --------------------------------------------------------------------------- #
# Commit-history heuristics                                                    #
# --------------------------------------------------------------------------- #

GENERIC_COMMIT_MESSAGES: tuple[str, ...] = (
    "initial commit",
    "first commit",
    "update",
    "updates",
    "update files",
    "add files",
    "add files via upload",
    "fix",
    "fixes",
    "changes",
    "wip",
    "misc",
    "commit",
    "stuff",
    "final",
    "done",
    "cleanup",
    "refactor",
)

# --------------------------------------------------------------------------- #
# Speculative model-attribution profiles                                       #
# --------------------------------------------------------------------------- #

# WARNING: this is the most unreliable signal in the system. Each profile is a
# bag of soft stylistic tendencies. Weights are tiny and confidence is always
# reported as low. Treat output as entertainment-grade, not evidence.
ATTRIBUTION_PROFILES: dict[str, dict[str, object]] = {
    "chatgpt": {
        "label": "ChatGPT / GPT-family",
        "phrases": ("certainly!", "sure!", "here's", "let's", "i hope this helps", "feel free"),
        "tends_to": ("emoji in headings", "numbered step explanations", "verbose docstrings"),
    },
    "claude": {
        "label": "Claude-family",
        "phrases": ("i'll", "let me", "here's a", "this implementation", "note that"),
        "tends_to": ("structured comments", "thorough error handling", "type hints"),
    },
    "gemini": {
        "label": "Gemini-family",
        "phrases": ("here is", "you can use", "the following code", "this snippet"),
        "tends_to": ("concise comments", "markdown-heavy docs"),
    },
    "copilot": {
        "label": "GitHub Copilot / inline completion",
        "phrases": (),
        "tends_to": ("short inline completions", "boilerplate repetition", "few comments"),
    },
    "other_llm": {
        "label": "Other / unknown LLM",
        "phrases": (),
        "tends_to": (),
    },
}
