#!/usr/bin/env python3
"""Collect real AI-generated repositories from GitHub (best-effort, label-noisy).

Searches the public GitHub API for repos that advertise an AI builder/tool in
their README or topics (bolt.new, Lovable, v0, ChatGPT, Claude, Cursor, ...),
which is strong (not perfect) evidence the code was AI-generated. Writes a JSON
manifest of candidates; cloning/sampling is done separately.

Unauthenticated search is rate-limited (~10 req/min); set GITHUB_TOKEN to raise
it. Provenance is heuristic — see docs/limitations.md.
"""
from __future__ import annotations

import json
import os
import time
import urllib.request

QUERIES = [
    ('"generated with bolt.new" in:readme', "bolt"),
    ('"bolt.new" in:readme', "bolt"),
    ('"built with lovable" in:readme', "lovable"),
    ('"lovable.dev" in:readme', "lovable"),
    ('"generated by v0" in:readme', "v0"),
    ('"v0.dev" in:readme', "v0"),
    ('"created with v0" in:readme', "v0"),
    ('"Generated with Claude Code" in:readme', "claude_code"),
    ('"made with cursor" in:readme', "cursor"),
    ('"this app was built with chatgpt" in:readme', "chatgpt"),
    ("topic:ai-generated", "topic"),
    ("topic:lovable", "lovable"),
    ("topic:built-with-bolt", "bolt"),
    ("topic:v0", "v0"),
]


def _search(q: str, token: str | None) -> list[dict]:
    url = (
        "https://api.github.com/search/repositories?q="
        + urllib.parse.quote(q)
        + "&per_page=40&sort=updated"
    )
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json",
                                               "User-Agent": "aipd-collector"})
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r).get("items", [])
    except Exception as exc:  # noqa: BLE001
        print(f"  query failed ({q[:40]}): {exc}")
        return []


def main() -> int:
    token = os.environ.get("GITHUB_TOKEN")
    found: dict[str, dict] = {}
    for q, marker in QUERIES:
        items = _search(q, token)
        print(f"{q[:48]:50} -> {len(items)}")
        for it in items:
            fn = it["full_name"]
            if fn in found:
                continue
            found[fn] = {
                "full_name": fn,
                "clone_url": it["clone_url"],
                "marker": marker,
                "stars": it.get("stargazers_count", 0),
                "size_kb": it.get("size", 0),
                "language": it.get("language"),
                "description": (it.get("description") or "")[:120],
            }
        time.sleep(0 if token else 7)  # respect unauth rate limit

    out = "/tmp/realai/candidates.json"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        json.dump(list(found.values()), f, indent=2)
    print(f"\nunique candidate repos: {len(found)} -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
